### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Creepers-Help** [markmandel/tmux-intellij#4]
Error processing command: [tmux, list-sessions, -F #{session_name}: #{?session_attached,(attached),(detached)}:  #{session_windows} windows ]

Error processing command: [tmux, list-sessions, -F #{session_name}: #{?session_attached,(attached),(detached)}:  #{session_windows} windows ]
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
    at com.compoundtheory.intellij.tmux.system.CommandUtils.executeCommand(CommandUtils.java:56)
    at com.compoundtheory.intellij.tmux.Tmux.listSessions(Tmux.java:45)
    at com.compoundtheory.intellij.tmux.actions.SelectPaneActionGroup.getChildren(SelectPaneActionGroup.java:51)
    at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:224)
    at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:249)
    at com.intellij.openapi.actionSystem.impl.Utils.b(Utils.java:208)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:146)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:85)
    at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:279)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.g(ActionMenu.java:281)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.access$400(ActionMenu.java:41)
    at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:235)
    at javax.swing.JMenu.fireMenuSelected(JMenu.java:1037)
    at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1117)
    at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:349)
    at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:232)
    at javax.swing.JMenu.setSelected(JMenu.java:305)
    at javax.swing.JMenu.menuSelectionChanged(JMenu.java:1186)
    at com.intellij.openapi.actionSystem.impl.ActionMenu.menuSelectionChanged(ActionMenu.java:209)
    at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
    at javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:526)
    at java.awt.Component.processMouseEvent(Component.java:6534)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4686)
    at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4665)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4514)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by markmandel** [comment]
Yeah,

This error gets thrown if there isn't an existing tmux session running.  I usually do have one always running, so this doesn't tend to be an issue for me.

If you start a tmux session, this will go away. But yeah, I should stop it from erroring out in the first place.

**Comment by Creepers-Help** [comment]
I had a TMUX session

**Comment by Creepers-Help** [comment]
sense removed plugin

**Comment by markmandel** [comment]
Without more details, and steps to reproduce, I can't really solve this I'm sorry to say :(

You haven't even given me what version of IntelliJ you were using.

**Comment by Creepers-Help** [comment]
It is fine, thank you anyway.
